#!/bin/bash
#SBATCH -N 4 --constraint="ib:fdr&cpu_model:E5-2660_v3" --exclude="cn211"

module load gcc/4.9.3 openmpi/1.10.0-gcc_4.9.3

export GASNET_USE_XRC=0
export OMPI_MCA_btl="sm,openib,self"
export OMPI_MCA_mpi_warn_on_fork=0
export LD_LIBRARY_PATH=${HOME}/opt/gasnet/1.26.4/lib/:$LD_LIBRARY_PATH
export GASNET_BACKTRACE=1  

mkdir -p ${HOME}/local/benchmarks/pennant/xeonE5-2660v3/pennant-spmd/leblanc/leblanc
cd ${HOME}/local/benchmarks/pennant/xeonE5-2660v3/pennant-spmd/leblanc/leblanc
cp ${HOME}/gitlab/pennant-spmd/pennant .
cp ${HOME}/gitlab/pennant-spmd/test/leblanc/leblanc_long4x30.pnt leblanc.pnt

mpirun -n 8 --map-by ppr:1:socket --bind-to socket ./pennant 32 ./leblanc.pnt \
 -ll:cpu 4 -ll:util 3 -ll:dma 1 -ll:csize 5000 2>&1 | tee leblanc.4x8
