#!/bin/bash
#SBATCH -N1 --cores-per-socket=10 --sockets-per-node=2 --constraint="haswell&ib_fdr"

module load gcc/4.9.3 openmpi/1.10.0-gcc_4.9.3

export GASNET_USE_XRC=0
export OMPI_MCA_btl="sm,openib,self"
export OMPI_MCA_mpi_warn_on_fork=0
export LD_LIBRARY_PATH=${HOME}/opt/gasnet/1.26.4/lib/:$LD_LIBRARY_PATH
export GASNET_BACKTRACE=1  


mkdir -p ${HOME}/local/regression/pennant/noh19
cd ${HOME}/local/regression/pennant/noh19
cp ${HOME}/gitlab/pennant-spmd//pennant . 
cp ${HOME}/gitlab/pennant-spmd/test/noh/noh.pnt  . 
mpirun -n 1 --map-by ppr:1:node --bind-to none ./pennant 19 noh.pnt -ll:cpu 19
