#!/bin/bash
#SBATCH -N1 --constraint="ib_fdr,e5-2660_v3"

module load gcc/4.9.3 openmpi/1.10.0-gcc_4.9.3

export GASNET_USE_XRC=0
export OMPI_MCA_btl="sm,openib,self"
export OMPI_MCA_mpi_warn_on_fork=0
export LD_LIBRARY_PATH=${HOME}/opt/gasnet/1.26.4/lib/:$LD_LIBRARY_PATH
export GASNET_BACKTRACE=1  


mkdir -p ${HOME}/local/regression/pennant/nohpoly29
cd ${HOME}/local/regression/pennant/nohpoly29
cp ${HOME}/gitlab/pennant-spmd//pennant . 
cp ${HOME}/gitlab/pennant-spmd/test/nohpoly/nohpoly.pnt  . 
mpirun -n 1 --map-by ppr:1:node --bind-to none ./pennant 29 nohpoly.pnt -ll:cpu 29
