#!/bin/bash
#SBATCH -N1 --constraint="ib_fdr"

module load gcc/4.9.3 openmpi/1.10.0-gcc_4.9.3

export GASNET_USE_XRC=0
export OMPI_MCA_mpi_paffinity_alone=0 
export OMPI_MCA_rmaps_base_loadbalance=1
export OMPI_MCA_btl="sm,openib,self"
export OMPI_MCA_mpi_warn_on_fork=0
export LD_LIBRARY_PATH=${HOME}/opt/gasnet/1.24.0-hack/lib/:$LD_LIBRARY_PATH
export GASNET_BACKTRACE=1  


mkdir -p ${HOME}/local/regression/pennant/nohsmall  #${SLURM_JOB_ID}
cd ${HOME}/local/regression/pennant/nohsmall  #${SLURM_JOB_ID}
cp ${HOME}/gitlab/pennant-spmd//pennant . 
cp ${HOME}/gitlab/pennant-spmd/test/nohsmall/nohsmall.pnt  . 
/home/jgraham/opt/gasnet/1.24.0-hack/bin/gasnetrun_ibv -n 4 -spawner=mpi ./pennant 1 nohsmall.pnt -ll:cpu 1 -ll:dma 3 -ll:csize 10000
