#!/usr/bin/perl

$phase = 0;

if ($phase == 0) {
system("rm -rf /home/jgraham/local/regression/pennant/leblanc") == 0
	or die "Unable to clean cache";
system("rm -rf /home/jgraham/local/regression/pennant/noh") == 0
	or die "Unable to clean cache";
system("rm -rf /home/jgraham/local/regression/pennant/nohsmall") == 0
	or die "Unable to clean cache";
system("rm -rf /home/jgraham/local/regression/pennant/sedov") == 0
	or die "Unable to clean cache";
system("rm -rf /home/jgraham/local/regression/pennant/sedovsmall") == 0
	or die "Unable to clean cache";

system("sbatch leblanc_serial") == 0
	or die "Unable to clean cache";
system("sbatch noh_serial") == 0
	or die "Unable to clean cache";
system("sbatch nohsmall_serial") == 0
	or die "Unable to clean cache";
system("sbatch sedov_serial") == 0
	or die "Unable to clean cache";
system("sbatch sedovsmall_serial") == 0
	or die "Unable to clean cache";
}


if ($phase == 1) {
system("./pennant_regression.py /home/jgraham/github/PENNANT/test/leblanc/leblanc.xy.std /home/jgraham/local/regression/pennant/leblanc/leblanc.xy") == 0
	or die "\033[31mFAIL\033[0m";

system("./pennant_regression.py /home/jgraham/github/PENNANT/test/noh/noh.xy.std /home/jgraham/local/regression/pennant/noh/noh.xy") == 0
	or die "\033[31mFAIL\033[0m";

system("./pennant_regression.py /home/jgraham/github/PENNANT/test/nohsmall/nohsmall.xy.std /home/jgraham/local/regression/pennant/nohsmall/nohsmall.xy") == 0
	or die "\033[31mFAIL\033[0m";

system("./pennant_regression.py /home/jgraham/github/PENNANT/test/sedov/sedov.xy.std /home/jgraham/local/regression/pennant/sedov/sedov.xy") == 0
	or die "\033[31mFAIL\033[0m";

system("./pennant_regression.py /home/jgraham/github/PENNANT/test/sedovsmall/sedovsmall.xy.std /home/jgraham/local/regression/pennant/sedovsmall/sedovsmall.xy") == 0
	or die "\033[31mFAIL\033[0m";
}

