#!/bin/bash
#SBATCH -N1 --constraint="ib:fdr&cpu_model:E5-2660_v3"

module load gcc/4.9.3 openmpi/1.10.0-gcc_4.9.3

export GASNET_USE_XRC=0
export OMPI_MCA_btl="sm,openib,self"
export OMPI_MCA_mpi_warn_on_fork=0
export LD_LIBRARY_PATH=${HOME}/opt/gasnet/1.26.4/lib/:$LD_LIBRARY_PATH
export GASNET_BACKTRACE=1  

mkdir -p ${HOME}/local/benchmarks/pennant/xeonE5-2660v3/pennant-spmd/sedovbig/sedovbig.1x2
cd ${HOME}/local/benchmarks/pennant/xeonE5-2660v3/pennant-spmd/sedovbig/sedovbig.1x2
cp ${HOME}/gitlab/pennant-spmd/pennant .
cp ${HOME}/gitlab/pennant-spmd/test/sedovbig/sedovbig3x30.pnt sedovbig.pnt

mpirun -n 2 --map-by ppr:1:socket --bind-to socket ./pennant 2 ./sedovbig.pnt \
 -ll:cpu 1 -ll:util 3 -ll:dma 1 -ll:csize 10000 2>&1 | tee sedovbig.1x2
# -ll:cpu 1 -ll:util 3 -ll:dma 1 -ll:csize 10000 -hl:prof 1 -logfile prof_%.log 2>&1 | tee sedovbig.1x2
#-ll:cpu 2 -lg:warn -ll:csize 10000 2>&1 | tee sedovbig.1x2
#-ll:cpu 17 -ll:util 2 -ll:dma 1 -hl:prof 2 -logfile prof_%.log 2>&1 | tee sedovbig.1x2
