#!/bin/bash
#SBATCH -N1 --cores-per-socket=10 --sockets-per-node=2 --partition=general
module load gcc/4.9.3 openmpi/1.10.0-gcc_4.9.3

mkdir -p ${HOME}/local/regression/pennant/sedov  #${SLURM_JOB_ID}
cd ${HOME}/local/regression/pennant/sedov  #${SLURM_JOB_ID}
cp ${HOME}/github/PENNANT/build/pennant . 
cp ${HOME}/github/PENNANT/test/sedov/sedov.pnt  . 
mpirun -n 1 ./pennant sedov.pnt
