#!/bin/bash
#SBATCH -N1 --constraint="ib:fdr&cpu_model:E5-2660_v3"

module load gcc/4.9.3 openmpi/1.10.0-gcc_4.9.3

export GASNET_USE_XRC=0
export OMPI_MCA_btl="sm,openib,self"
export OMPI_MCA_mpi_warn_on_fork=0
export LD_LIBRARY_PATH=${HOME}/opt/gasnet/1.26.4/lib/:$LD_LIBRARY_PATH
export GASNET_BACKTRACE=1  

mkdir -p ${HOME}/local/benchmarks/pennant/xeonE5-2660v3/pennant-spmd/sedovbig/sedovbig.1x8
cd ${HOME}/local/benchmarks/pennant/xeonE5-2660v3/pennant-spmd/sedovbig/sedovbig.1x8
cp ${HOME}/gitlab/pennant-spmd/pennant .
cp ${HOME}/gitlab/pennant-spmd/test/sedovbig/sedovbig3x30.pnt sedovbig.pnt

mpirun -n 2 --map-by ppr:1:socket --bind-to socket ./pennant 8 ./sedovbig.pnt \
 -ll:cpu 4 -ll:util 3 -ll:dma 1 -ll:csize 5000 2>&1 | tee sedovbig.1x8
# -ll:cpu 16 -ll:util 3 -ll:dma 1 -ll:csize 5000 -hl:prof 1 -logfile prof_%.log 2>&1 | tee sedovbig.1x8
#-ll:cpu 8 -ll:util 2 -ll:dma 1 -hl:spy -logfile spy_%.log 2>&1 | tee sedovbig.1x8
