#!/bin/bash
#SBATCH -N1 --cores-per-socket=10 --sockets-per-node=2 --partition=general --constraint="baseboard_supermicro&cpu_intel&haswell&e5-2660_v3&2.60ghz&numa2&smt&ib_fdr&10gbe"

module load gcc/4.9.3 openmpi/1.10.0-gcc_4.9.3

export GASNET_USE_XRC=0
export OMPI_MCA_mpi_paffinity_alone=0 
export OMPI_MCA_rmaps_base_loadbalance=1
export OMPI_MCA_btl="sm,openib,self"
export OMPI_MCA_mpi_warn_on_fork=0
export LD_LIBRARY_PATH=${HOME}/opt/gasnet/1.24.0-hack/lib/:$LD_LIBRARY_PATH
export GASNET_BACKTRACE=1  


mkdir -p ${HOME}/local/regression/pennant/sedov4  #${SLURM_JOB_ID}
cd ${HOME}/local/regression/pennant/sedov4  #${SLURM_JOB_ID}
cp ${HOME}/github/PENNANT//pennant . 
cp ${HOME}/github/PENNANT/test/sedov/sedov.pnt  . 
#/home/jgraham/opt/gasnet/1.24.0-hack/bin/gasnetrun_ibv -n 4 -spawner=mpi ./pennant sedov.pnt -ll:cpu 1 -ll:dma 3 -ll:csize 10000
#mpirun -n 7 --bind-to none ./pennant sedov.pnt -ll:cpu 4 -ll:dma 3 -ll:csize 10000
mpirun -n 4 ./pennant sedov.pnt
